app:
  image:
    repository: obsedo-app
    tag: latest
    pullPolicy: Never
  replicaCount: 1
  service:
    type: NodePort
    port: 80
    targetPort: 5000
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  config:
    flaskApp: "run.py"
    flaskEnv: "production"

postgres:
  image:
    repository: postgres
    tag: "15"
  user: postgres
  password: postgres
  database: obsedo_dev
  storage: 1Gi
  storageClassName: standard
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

secret:
  secretKey: "defaultsecret"

observability:
  enabled: true
  prometheus:
    image:
      repository: prom/prometheus
      tag: "v2.51.2"
    retentionTime: 24h
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
  grafana:
    image:
      repository: grafana/grafana
      tag: "10.4.2"
    service:
      type: NodePort
      port: 3000
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
