services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: obsedo_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  obsedo-app:
    build: .
    ports:
      - "80:5000"
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  postgres_data:
