apiVersion: v1
kind: ConfigMap
metadata:
  name: obsedo-config
  labels:
    {{- include "obsedo.labels" . | nindent 4 }}
data:
  FLASK_APP: {{ .Values.app.config.flaskApp | quote }}
  FLASK_ENV: {{ .Values.app.config.flaskEnv | quote }}
