{{- if .Values.observability.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  labels:
    {{- include "obsedo.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: false

  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: obsedo
        orgId: 1
        type: file
        disableDeletion: false
        updateIntervalSeconds: 30
        options:
          path: /var/lib/grafana/dashboards
{{- end }}
