apiVersion: v1
kind: Secret
metadata:
  name: obsedo-secret
  labels:
    {{- include "obsedo.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ include "obsedo.databaseUrl" . | b64enc | quote }}
  SECRET_KEY: {{ .Values.secret.secretKey | b64enc | quote }}
